
const cars = [
    {
        img: './img/120i.jpg',
        series: 'Series 1',
        model: '120d',
        fuel: 'diesel',
        price: 30000,
    },
    {
        img: './img/m135.webp',
        series: 'Series 1',
        model: 'M135i',
        fuel: 'benzine',
        price: 50000,
    },
    {
        img: './img/230i.avif',
        series: 'Series 2',
        model: '230i',
        fuel: 'benzine',
        price: 40000,
    },
    {
        img: './img/2-active-tourer.jpg',
        series: 'Series 2',
        model: 'Active Tourer',
        fuel: 'diesel',
        price: 35000,
    },
    {
        img: './img/m240i.jpg',
        series: 'Series 2',
        model: 'M240i',
        fuel: 'benzine',
        price: 74000,
    },
    {
        img: './img/320i',
        series: 'Series 3',
        model: '320i',
        fuel: 'benzine',
        price: 44000,
    },
    {
        img: './img/320i-touring.jpg',
        series: 'Series 3',
        model: '320d Touring',
        fuel: 'diesel',
        price: 47000,
    },
    {
        img: './img/m340i.webp',
        series: 'Series 3',
        model: 'M340i',
        fuel: 'benzine',
        price: 83000,
    },
    {
        img: './img/420i-coupe',
        series: 'Series 4',
        model: '420i Coupe',
        fuel: 'benzine',
        price: 50000,
    },
    {
        img: './img/430i-grand-coupe.webp',
        series: 'Series 4',
        model: '430d Coupe',
        fuel: 'diesel',
        price: 58000,
    },
    {
        img: './img/m4-csl.avif',
        series: 'Series 4',
        model: 'M4 CSL',
        fuel: 'benzine',
        price: 100000,
    },
    {
        img: './img/530i.jpg',
        series: 'Series 5',
        model: '530i',
        fuel: 'benzine',
        price: 60000,
    },
    {
        img: './img/520d-touring.jpg',
        series: 'Series 5',
        model: '520d Touring',
        fuel: 'diesel',
        price: 65000,
    },
    {
        img: './img/m5.jpg',
        series: 'Series 5',
        model: 'M5',
        fuel: 'benzine',
        price: 120000,
    },
]

